add float16 mode and bug fix around image stacks
sethaxen/MRC.jl pull request #17
Opened 2023-06-05 05:42 UTC by k-haru

Hi,

I added f16 mode and bug fix around image stacks.
It could read relion_project outputs like projection stacks.

2023-06-05 13:37 UTC, sethaxen requested changes
Thanks for the PR. This seems to just be missing tests.

2023-06-05 13:37 UTC, sethaxen commented on src/header.jl
> +        ifelse(nz == 1, Image, ImageStack)
Can you add a test that catches this bug?

2023-06-05 13:37 UTC, sethaxen commented on src/MRCFile.jl
> +    Int32(12) => Float16
Can you add some test data and a test that loads it?

2023-06-05 15:53 UTC, k-haru commented
How about this?
It should be OK.

2023-06-19 17:42 UTC, closed without merging

2023-06-19 18:32 UTC, sethaxen commented
Hi @k-haru, why was this closed?